import type { FounderProfile, MarketSignal, OpportunityCard } from './types'

export const seedFounderProfile: FounderProfile = {
  id: 'founder-001',
  name: 'Алексей Громов',
  experience_domains: ['b2b-продажи', 'логистика', 'малый бизнес'],
  skills: {
    'продажи': 'expert',
    'переговоры': 'strong',
    'продуктовое мышление': 'intermediate',
    'разработка': 'beginner',
  },
  distribution_access: ['личная сеть', 'холодные звонки', 'telegram'],
  preferred_models: ['услуги', 'подписка'],
  time_horizon_months: 12,
  manual_work_tolerance: 'high',
  sales_cycle_tolerance: 'medium_ok',
}

export const seedSignals: MarketSignal[] = [
  {
    id: 'signal-001',
    raw_signal_id: 'raw-001',
    audience: 'Малый бизнес в рознице (5–50 сотрудников)',
    problem: 'Не могут нормально отследить, какой товар реально продаётся, а какой лежит мёртвым грузом. Excel не справляется, нормальные системы дорогие.',
    current_workaround: 'Ведут таблицы вручную, раз в месяц делают инвентаризацию наугад.',
    evidence_strength: 'strong',
    frequency: 'pervasive',
    urgency: 'high',
    confidence: 0.85,
    normalized_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'signal-002',
    raw_signal_id: 'raw-002',
    audience: 'Небольшие логистические компании (10–30 машин)',
    problem: 'Водители опаздывают, диспетчеры не знают где машина, клиенты звонят и жалуются. Нормальная система трекинга стоит как самолёт.',
    current_workaround: 'WhatsApp-переписка между диспетчером и водителями.',
    evidence_strength: 'moderate',
    frequency: 'frequent',
    urgency: 'high',
    confidence: 0.72,
    normalized_at: '2026-03-05T14:00:00Z',
  },
  {
    id: 'signal-003',
    raw_signal_id: 'raw-003',
    audience: 'Фрилансеры и небольшие агентства',
    problem: 'Клиенты постоянно просят правки, которые выходят за рамки договора. Нет инструмента, чтобы красиво зафиксировать объём и сказать "это платно".',
    current_workaround: 'Конфликт в переписке, иногда просто делают бесплатно чтобы не ссориться.',
    evidence_strength: 'moderate',
    frequency: 'frequent',
    urgency: 'medium',
    confidence: 0.68,
    normalized_at: '2026-03-10T09:00:00Z',
  },
]

export const seedOpportunities: OpportunityCard[] = [
  {
    id: 'opp-001',
    title: 'Простая аналитика остатков для малой розницы',
    problem: 'Малый розничный бизнес не может отследить движение товара без дорогих систем.',
    audience: 'Владельцы небольших розничных магазинов (5–50 сотрудников)',
    founder_profile_id: 'founder-001',
    signal_ids: ['signal-001'],
    pattern_ids: [],
    scoring_run_id: 'score-001',
    pain_score: 0.82,
    willingness_to_pay: 'high',
    founder_fit_score: 0.74,
    pattern_score: 0.61,
    entry_feasibility_score: 0.79,
    overall_score: 0.76,
    confidence: 0.85,
    risks: [
      'Высокая конкуренция со стороны 1С и МойСклад',
      'Долгий цикл принятия решения у владельцев магазинов',
      'Требует интеграции с кассой — технически сложно на старте',
    ],
    recommended_entry_mode: 'manual_first',
    first_offer: 'Предложи бесплатный аудит остатков за 1 день — приедь, посмотри, покажи где теряются деньги.',
    first_test: 'Найди 5 владельцев магазинов из своей сети, предложи бесплатный аудит. Если 3 из 5 согласятся — спрос есть.',
    created_at: '2026-03-15T12:00:00Z',
  },
  {
    id: 'opp-002',
    title: 'Диспетчерский чат-инструмент для малой логистики',
    problem: 'Небольшие логистические компании управляют машинами через WhatsApp.',
    audience: 'Диспетчеры небольших транспортных компаний (10–30 машин)',
    founder_profile_id: 'founder-001',
    signal_ids: ['signal-002'],
    pattern_ids: [],
    scoring_run_id: 'score-002',
    pain_score: 0.71,
    willingness_to_pay: 'medium',
    founder_fit_score: 0.65,
    pattern_score: 0.55,
    entry_feasibility_score: 0.62,
    overall_score: 0.64,
    confidence: 0.72,
    risks: [
      'Владельцы привыкли к WhatsApp и не хотят менять процесс',
      'GPS-трекинг требует мобильного приложения — MVP сложнее',
    ],
    recommended_entry_mode: 'productized_service',
    first_offer: 'Настрой им Telegram-бота для диспетчера за фиксированную плату — быстро, без разработки.',
    first_test: 'Поговори с 3 диспетчерами. Готовы ли они платить 3–5 тыс. руб./мес. за структурированный чат вместо WhatsApp?',
    created_at: '2026-03-15T12:05:00Z',
  },
]
